### ISSUE TITLE
Copied Project

### ISSUE THREAD

**Issue by Nanomotion** [Torotv/AreUOnlinev1#1]
This is a copy of @WorldLanguages's https://github.com/WorldLanguages/isOnlineBETA. Please give proper credits to them or delete this as they have worked hard on their repository, and all you have done is Made It better!!!!! Great Job! 28

**Comment by Torotv** [comment]
Thank You!

**Comment by Nanomotion** [comment]
I'm going to contact the copyright owner about this, and anyone who else had their repos copied.

**Comment by redmangospros** [comment]
Okay!
